Repository ShyPolarBear/Android, pull requests merged in 2023-11, with the labels that each got.

#86 [WBS-242]design: Quiz 화면에서 하단 부 여백 나오는 방식 조정
  presentation/src/main/res/layout/fragment_quiz_main.xml
  presentation/src/main/res/layout/item_quiz_main_recent_feed.xml
Labels: bug

#88 [WBS-243]Feature/apply log out
  app/src/main/java/com/shypolarbear/android/di/ApiModule.kt
  app/src/main/java/com/shypolarbear/android/di/RepositoryModule.kt
  app/src/main/java/com/shypolarbear/android/di/UseCaseModule.kt
  data/src/main/java/com/shypolarbear/data/api/InfoApi.kt
  data/src/main/java/com/shypolarbear/data/api/LogoutApi.kt
  data/src/main/java/com/shypolarbear/data/repositoryimpl/InfoRepoImpl.kt
  data/src/main/java/com/shypolarbear/data/repositoryimpl/LogoutRepoImpl.kt
  domain/src/main/java/com/shypolarbear/domain/model/more/CheckDuplicateNickNameResponse.kt
  domain/src/main/java/com/shypolarbear/domain/model/more/LogoutResponse.kt
  domain/src/main/java/com/shypolarbear/domain/repository/InfoRepo.kt
  domain/src/main/java/com/shypolarbear/domain/repository/LogoutRepo.kt
  domain/src/main/java/com/shypolarbear/domain/usecase/RequestLogoutUseCase.kt
  domain/src/main/java/com/shypolarbear/domain/usecase/more/RequestCheckDuplicateNickNameUseCase.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedWrite/FeedWriteFragment.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/more/MoreFragment.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/more/MoreViewModel.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/more/changemyinfo/ChangeMyInfoFragment.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/more/changemyinfo/ChangeMyInfoViewModel.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/more/dialog/LogOutDialog.kt
  presentation/src/main/java/com/shypolarbear/presentation/util/FunctionUtil.kt
  presentation/src/main/res/drawable/background_solid_gray_06_radius_15.xml
  presentation/src/main/res/layout/dialog_more_logout.xml
  presentation/src/main/res/layout/fragment_change_my_info.xml
  presentation/src/main/res/layout/fragment_feed_detail.xml
  presentation/src/main/res/layout/fragment_feed_write.xml
  presentation/src/main/res/layout/item_feed_no_image.xml
  presentation/src/main/res/navigation/nav_graph.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#92 [WBS-233]Feature/apply auto login
  presentation/src/main/java/com/shypolarbear/presentation/ui/join/JoinViewModel.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/join/pages/JoinNameFragment.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/main/MainActivity.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/quiz/main/QuizMainAdapter.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/quiz/main/QuizMainFragment.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/splash/SplashFragment.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/splash/SplashViewModel.kt
  presentation/src/main/res/layout/fragment_splash.xml
  presentation/src/main/res/layout/item_quiz_main_recent_feed.xml
  presentation/src/main/res/navigation/nav_graph.xml
Labels: bug, enhancement, feature

#93 Feature/fix reply writing msg
  presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/adapter/FeedCommentAdapter.kt
  presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
  presentation/src/main/res/layout/fragment_feed_detail.xml
  presentation/src/main/res/values/strings.xml
Labels: bug

#95 Feature/resize comment area size
  presentation/src/main/res/layout/item_feed.xml
  presentation/src/main/res/layout/item_feed_comment_normal.xml
Labels: bug
